import os
import numpy as np
import tensorflow as tf
from flask import Flask, render_template, jsonify, request
from tensorflow.keras.models import load_model

# Initialize the Flask Application
app = Flask(__name__)

# --- Configuration ---
# Get current working directory
BASE_DIR = os.getcwd()
# Path to the trained AI model (generated by the training script)
MODEL_PATH = os.path.join(BASE_DIR, "model.keras") 

# Global Simulation State
# Default scenario is "NL" (No Leak / Normal)
CURRENT_SCENARIO = "NL"
AI_MODEL = None

# --- 1. Physics Engine (Synthetic Signal Generation) ---
def generate_synthetic_signal(scenario, length=4000):
    """
    Simulates the hydrophone sensor data based on the physics of the pipe state.
    
    Args:
        scenario (str): The current operating condition (NL, GL, LC, CC, OL).
        length (int): Number of data points (default 4000 for 0.5s sample).
        
    Returns:
        np.array: Normalized acoustic waveform.
    """
    # Create time vector
    t = np.linspace(0, 0.5, length)
    
    if scenario == "NL":
        # Normal Operation: Low frequency hum (50Hz) + low noise
        signal = 0.05 * np.sin(2 * np.pi * 50 * t) + np.random.normal(0, 0.02, length)
        
    elif scenario == "GL":
        # Gasket Leak: Joint failure often creates harmonic oscillations (150Hz + 220Hz)
        signal = 0.2 * np.sin(2 * np.pi * 150 * t) + 0.15 * np.sin(2 * np.pi * 220 * t) + np.random.normal(0, 0.05, length)
        
    elif scenario == "LC":
        # Longitudinal Crack: High frequency structural transient (1200Hz)
        signal = 0.1 * np.sin(2 * np.pi * 1200 * t) + np.random.normal(0, 0.1, length)
        
    elif scenario == "CC":
        # Circumferential Crack: Similar to LC but distinct frequency signature (1100Hz)
        # Note: This spectral overlap makes AI classification challenging (See Confusion Matrix)
        signal = 0.08 * np.sin(2 * np.pi * 1100 * t) + np.random.normal(0, 0.1, length)
        
    elif scenario == "OL":
        # Orifice Leak: High intensity "Jetting" sound (800Hz) + high turbulence noise
        signal = 0.3 * np.sin(2 * np.pi * 800 * t) + np.random.normal(0, 0.2, length)
        
    else:
        # Fallback silence
        signal = np.zeros(length)
        
    # Normalize signal to keep amplitude between -1 and 1
    return signal / (np.max(np.abs(signal)) + 1e-6)

# --- 2. Model Loader ---
def load_ai_model():
    """
    Attempts to load the trained Keras model. 
    If model.keras is missing, the system will run in pure simulation mode.
    """
    global AI_MODEL
    try:
        if os.path.exists(MODEL_PATH):
            print(f"🔄 Loading AI Model from: {MODEL_PATH}...")
            AI_MODEL = load_model(MODEL_PATH)
            print("✅ AI Model Loaded.")
        else:
            print("⚠️ 'model.keras' not found. Running Simulation Mode.")
    except Exception as e:
        print(f"❌ Error: {e}")

# --- 3. Routes ---

@app.route('/')
def index():
    """Renders the Digital Twin Interface."""
    return render_template('index.html')

@app.route('/api/set_scenario', methods=['POST'])
def set_scenario():
    """
    API Endpoint: Receives command from UI to change pipe condition.
    Example: Switch from Normal (NL) to Leak Simulation (OL).
    """
    global CURRENT_SCENARIO
    data = request.json
    CURRENT_SCENARIO = data.get('type', 'NL')
    return jsonify({"status": "updated", "current": CURRENT_SCENARIO})

@app.route('/api/predictive_analytics')
def predictive_analytics():
    """
    Core Digital Twin Loop:
    1. Generates physics-based sensor data.
    2. Runs AI Inference (CNN-LSTM) to classify health.
    3. Calculates secondary metrics (Pressure, Acoustics, Vibration).
    4. Returns JSON payload to update the 3D Interface.
    """
    # A. Generate Data
    raw_signal = generate_synthetic_signal(CURRENT_SCENARIO)
    
    # B. AI Inference (The "Brain")
    prediction_label = CURRENT_SCENARIO # Default to truth if no model
    confidence = 98.5 # Default confidence
    
    if AI_MODEL:
        try:
            # Reshape for CNN input (Batch, TimeSteps, Channels)
            input_tensor = raw_signal.reshape(1, 4000, 1)
            prediction = AI_MODEL.predict(input_tensor, verbose=0)
            
            classes = ["CC", "GL", "LC", "NL", "OL"]
            pred_idx = np.argmax(prediction)
            prediction_label = classes[pred_idx]
            confidence = float(prediction[0][pred_idx]) * 100
        except Exception as e:
            print(f"Inference Error: {e}")

    # C. Physics Simulation (Secondary Telemetry)
    # Calculate Root Mean Square (RMS) for vibration intensity
    rms = np.sqrt(np.mean(raw_signal**2))
    pressure_base = 2.15 
    
    if prediction_label != "NL":
        # Leaks cause pressure drops proportional to leak size (RMS)
        pressure = max(0.5, pressure_base - (rms * 2.5))
        # Acoustics increase with leak size
        acoustic_db = -20 + (rms * 50)
    else:
        # Normal operation allows slight pressure fluctuation
        pressure = pressure_base + np.random.normal(0, 0.01)
        acoustic_db = -80 + (rms * 10)

    # D. Signal Processing (FFT) for UI Visualization
    # Fast Fourier Transform to show frequency spectrum in dashboard
    fft_spectrum = np.abs(np.fft.rfft(raw_signal))[:50].tolist()

    return jsonify({
        "scenario": CURRENT_SCENARIO,
        "ai_prediction": prediction_label,
        "confidence": f"{confidence:.1f}",
        "telemetry": {
            "pressure": f"{pressure:.2f} Bar",
            "acoustic": f"{acoustic_db:.1f} dB",
            "vibration": f"{rms:.3f} g"
        },
        "fft": fft_spectrum
    })

if __name__ == "__main__":
    load_ai_model()
    app.run(debug=True, port=5000)